Reduced number of pipes to avoid actions inconsistency

diff --git a/.github/workflows/pull.yml b/.github/workflows/pull.yml
--- a/.github/workflows/pull.yml
+++ b/.github/workflows/pull.yml
@@ -76,9 +76,9 @@ jobs:
           ${{matrix.immuclient}} login --username immudb --password immudb || { echo "Test #2 Login (Default credentials) Failed"; exit 1; }
           ${{matrix.immuclient}} safeset test3 githubaction || { echo "Test #3 Failed to safeset simple values"; exit 1; }
           sg=$(${{matrix.immuclient}} safeget test3)
-          echo "$sg" |grep -q "githubaction" || { echo "Test #4 Failed safeget responded with $sg"; exit 1; }
-          echo "$sg" |grep -q  "verified" || { echo "Test #5 Failed safeset didn't get verified"; exit 1; }
-          echo "$sg" |grep -q "true" || { echo "Test #5 Failed safeset didn't get verified"; exit 1; }
+          grep -q "githubaction" <<< $sg || { echo "Test #4 Failed safeget responded with $sg"; exit 1; }
+          grep -q  "verified" <<< $sg || { echo "Test #5 Failed safeset didn't get verified"; exit 1; }
+          grep -q "true" <<< $sg || { echo "Test #5 Failed safeset didn't get verified"; exit 1; }
         shell: bash
 
   test-webconsole:
@@ -106,9 +106,9 @@ jobs:
           immuclient login --username immudb --password immudb || { echo "Test #2 Login (Default credentials) Failed"; exit 1; }
           immuclient safeset test3 githubaction || { echo "Test #3 Failed to safeset simple values"; exit 1; }
           sg=$(immuclient safeget test3)
-          echo "$sg" |grep -q "githubaction" || { echo "Test #4 Failed safeget responded with $sg"; exit 1; }
-          echo "$sg" |grep -q  "verified" || { echo "Test #5 Failed safeset didn't get verified"; exit 1; }
-          echo "$sg" |grep -q "true" || { echo "Test #5 Failed safeset didn't get verified"; exit 1; }
+          grep -q "githubaction" <<< $sg || { echo "Test #4 Failed safeget responded with $sg"; exit 1; }
+          grep -q  "verified" <<< $sg || { echo "Test #5 Failed safeset didn't get verified"; exit 1; }
+          grep -q "true" <<< $sg || { echo "Test #5 Failed safeset didn't get verified"; exit 1; }
           # Find <title>immudb webconsole</title>
           webconsole_page=$(curl -s localhost:8080) || { echo "Test #6 web console unreachable"; exit 1; }
           grep -q "<title>immudb webconsole</title>" <<< $webconsole_page || { echo "Test #7 Failed, web console reachable but title not found"; exit 1; }
